version: '3.5'

services:

  qmk_api:
    build: .
    ports:
     - "5000:5000"
    environment:
      S3_ACCESS_KEY: minio_dev
      S3_SECRET_KEY: minio_dev_secret
      REDIS_HOST: redis
      S3_HOST: http://minio:9000
      UPDATE_API: 'true'

  minio:
    image: minio/minio:RELEASE.2018-09-25T21-34-43Z
    volumes:
     - data:/data
    ports:
     - "9000:9000"
    environment:
     MINIO_ACCESS_KEY: minio_dev
     MINIO_SECRET_KEY: minio_dev_secret
     S3_ACCESS_KEY: minio_dev
     S3_SECRET_KEY: minio_dev_secret
    command: server minio_data

  redis:
    image: redis:4.0
    ports:
     - "6379:6379"

volumes:
    data:

